# Generated by Django 2.0.7 on 2018-07-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortit', '0002_auto_20180721_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
