# Generated by Django 2.0.7 on 2018-07-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortit', '0004_url_num_of_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
